### ISSUE TITLE
Pysinsy wheel won't build

### ISSUE THREAD

**Issue by Katistic** [r9y9/pysinsy#16] opened 2023-07-22 03:53 UTC
Happens with all pysinsy versions, using cython3.0.0 and tried other versions too

```
Error compiling Cython file:
      ------------------------------------------------------------
      ...

      cimport cython
      from libcpp.string cimport string
      from libcpp.vector cimport vector

      from sinsy cimport sinsy, label_strings
      ^
      ------------------------------------------------------------

      pysinsy\sinsy.pyx:13:0: 'sinsy.pxd' not found
```

This is then recursive and creates a lot more errors ending in a failed build
I have checked that pysinsy/sinsy/sinsy.pxd exists, so I don't know why this is happening

Tested with both ubuntu and windows

**Comment by karkirowle** [comment] 2023-08-07 21:21
I ran into the same error. I spent a few hour with this and not entirely sure what's causing it. File seems to be present.
@Katistic 's issues timing makes me think it's something with the new Cython version , but I haven't had a lot of success with rolling back to earlier Cython versions.

**Comment by macguyversmusic** [comment] 2023-08-18 21:28
![image](https://github.com/r9y9/pysinsy/assets/89907172/196d3807-4391-4fc2-b452-6830ea00cac0)
same thing on a vast instance with pytorch latest
same thing locally windows python3
same sort of error on colab hardware.

can we help in any way?? @r9y9 maybe if you can give a hint we can work to get this working across all the different demos.
to date i cannot make a single colab demo os nnsvs or pysinsy function.

i do have one notebook that seems to be using working pysinsy to call sinsy.jp via midi2voice but i dont know how i would figure out what to port from that colab to the current sinsy colab to make it work...

steps
new instance on vast.ai
apt update && apt upgrade && apt install cython build-essential
cd /root
git clone pysinsy
cd pysinsy
follow the rest of the instructions from the following:
![image](https://github.com/r9y9/pysinsy/assets/89907172/aff74bce-92b1-4420-a08b-ad6f4fa6f678)

can you confirm the numpy version it relies on please?

**Comment by AbdullahMustafa040** [comment] 2023-08-30 19:35
@Katistic did you find any solution?

**Comment by crlotwhite** [comment] 2023-09-19 07:36
The list of compile errors.
- [ ] "new operator can only be applied to a C++ class"
- [ ] "Python objects cannot be cast to pointers of primitive types"
- [ ] "Casting temporary Python object to non-numeric non-Python type"

"Deletion of non-Python, non-C++ object" was caused by other one.

**Comment by Katistic** [comment] 2023-10-01 15:46
Using #17 
![image](https://github.com/r9y9/pysinsy/assets/33645731/610acf6f-31dd-41b3-9dd6-98a7283a9b93)

**Comment by r9y9** [comment] 2023-10-09 03:05
should be fixed by https://github.com/r9y9/pysinsy/releases/tag/v0.0.5

**Closed by r9y9** 2023-10-09 03:05 UTC
